apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: rawfile.hamravesh.com
spec:
  attachRequired: false
  podInfoOnMount: true
{{- if semverCompare ">=1.16" .Capabilities.KubeVersion.Version }}
  volumeLifecycleModes:
    - Persistent
{{- end }}
